name: Feature/Fix continuous integration / deployment on clevercloud

on:
  workflow_dispatch:
  push:
    branches:
      - feature/*
      - fix/*

jobs:
  dependencies:
    uses: ./.github/workflows/dependencies.reusable.yml
    with:
      node-version: '16.13.1'

  build:
    needs: dependencies
    uses: ./.github/workflows/build-angular.reusable.yml
    with:
      build-directory-path: 'dist/portail-usager'

  validation:
    needs: dependencies
    uses: ./.github/workflows/validation.reusable.yml

  deploy:
    needs:
      - build
      - validation
    uses: ./.github/workflows/deploy-static-application-to-clevercloud.reusable.yml
    with:
      application-full-name: 'portail-usager-${GITHUB_REF##*/}'
    secrets:
      CLEVER_ORG_ID: ${{ secrets.CLEVER_ORG_ID }}
      CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
      CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}

  notify:
    needs:
      - deploy
    uses: ./.github/workflows/notify-deployment-mattermost.reusable.yml
    with:
      application-full-name: 'portail-usager-${GITHUB_REF##*/}'
      deployed-domain: ${{ needs.deploy.outputs.deployed-domain }}
    secrets:
      MATTERMOST_NOTIFY_HOOK_URL: ${{ secrets.MATTERMOST_NOTIFY_HOOK_URL }}
